module ReplacedPackages exposing (replacedPackages)

import Dict exposing (Dict)


replacedPackages : Dict String (List String)
replacedPackages =
    Dict.fromList
        [ ( "NoRedInk/elm-decode-pipeline", [ "NoRedInk/elm-json-decode-pipeline" ] )
        , ( "elm-community/elm-test", [ "elm-explorations/test" ] )
        , ( "elm-lang/animation-frame", [ "elm/browser" ] )
        , ( "elm-lang/core", [ "elm/core" ] )
        , ( "elm-lang/html", [ "elm/html" ] )
        , ( "elm-lang/http", [ "elm/http" ] )
        , ( "elm-lang/svg", [ "elm/svg" ] )
        , ( "elm-lang/virtual-dom", [ "elm/virtual-dom" ] )
        , ( "elm-tools/parser", [ "elm/parser" ] )
        , ( "evancz/elm-markdown", [ "elm-explorations/markdown" ] )
        , ( "evancz/url-parser", [ "elm/url" ] )
        , ( "mgold/elm-random-pcg", [ "elm/random" ] )
        , ( "ohanhi/keyboard-extra", [ "ohanhi/keyboard" ] )
        , ( "thebritican/elm-autocomplete", [ "ContaSystemer/elm-menu" ] )
        , ( "elm-community/linear-algebra", [ "elm-explorations/linear-algebra" ] )
        , ( "elm-community/webgl", [ "elm-explorations/webgl" ] )
        , ( "elm-lang/keyboard", [ "elm/browser" ] )
        , ( "elm-lang/dom", [ "elm/browser" ] )
        , ( "elm-lang/navigation", [ "elm/browser" ] )
        , ( "elm-lang/window", [ "elm/browser" ] )
        , ( "mpizenberg/elm-mouse-events", [ "mpizenberg/elm-pointer-events" ] )
        , ( "mpizenberg/elm-touch-events", [ "mpizenberg/elm-pointer-events" ] )
        , ( "ryannhg/elm-date-format", [ "ryannhg/date-format" ] )
        , ( "rtfeldman/hex", [ "rtfeldman/elm-hex" ] )
        , ( "elm-lang/mouse", [ "elm/browser" ] )
        , ( "avh4/elm-transducers", [ "avh4-experimental/elm-transducers" ] )
        , ( "dillonkearns/graphqelm", [ "dillonkearns/elm-graphql" ] )
        , ( "mgold/elm-date-format", [ "ryannhg/date-format" ] )
        , ( "justinmimbs/elm-date-extra", [ "justinmimbs/date", "rtfeldman/elm-iso8601-date-strings", "ryannhg/date-format" ] )
        , ( "mpizenberg/elm-debounce", [ "jinjor/elm-debounce" ] )
        ]
